# Generated by Django 5.0 on 2024-01-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_listing_price_remove_listing_watch_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
